import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { CompanySettings } from '../types';
import { getCompanySettings } from './storage';
import { cleanPhoneNumber } from './whatsapp';
import { customAlert } from './dialog';
import { getSystemLanguage, Language } from './i18n';

export interface AccountPdfOptions {
  title: string;
  subtitle?: string;
  accountName: string;
  accountCode?: string;
  accountType?: string;
  period?: string;
  date?: string;
  currency?: string;
  openingBalance?: number;
  totalDebit?: number;
  totalCredit?: number;
  closingBalance?: number;
  headers: string[];
  rows: (string | number)[][];
  totals?: { label: string; value: string | number; isDebit?: boolean; isCredit?: boolean }[];
  notes?: string;
  companySettings?: CompanySettings;
  lang?: Language;
}

/**
 * دالة لتوليد كود HTML منسق احترافياً للطباعة وتوليد الـ PDF عالي الدقة
 */
export function generateAccountHtmlDocument(opts: AccountPdfOptions): HTMLElement {
  const settings = opts.companySettings || getCompanySettings();
  const currentLang = opts.lang || getSystemLanguage();
  const isRtl = currentLang === 'ar';
  const dir = isRtl ? 'rtl' : 'ltr';

  const curr = opts.currency || settings.currency || (currentLang === 'ar' ? 'ج.م' : 'EGP');
  const locale = currentLang === 'ar' ? 'ar-EG' : currentLang === 'de' ? 'de-DE' : 'en-US';
  const currentDate = opts.date || new Date().toLocaleDateString(locale, { year: 'numeric', month: 'long', day: 'numeric' });
  const currentTime = new Date().toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' });

  const labels = {
    cr: currentLang === 'de' ? 'Handelsregister' : currentLang === 'en' ? 'Commercial Reg.' : 'سجل تجاري',
    vat: currentLang === 'de' ? 'Steuernummer' : currentLang === 'en' ? 'Tax / VAT ID' : 'الرقم الضريبي',
    phone: currentLang === 'de' ? 'Tel' : currentLang === 'en' ? 'Phone' : 'هاتف',
    reportDate: currentLang === 'de' ? 'Berichtsdatum' : currentLang === 'en' ? 'Report Date' : 'تاريخ التقرير',
    issueTime: currentLang === 'de' ? 'Ausgabezeit' : currentLang === 'en' ? 'Issue Time' : 'وقت الإصدار',
    currency: currentLang === 'de' ? 'Währung' : currentLang === 'en' ? 'Currency' : 'العملة المعتمدة',
    fiscalYear: currentLang === 'de' ? 'Geschäftsjahr' : currentLang === 'en' ? 'Fiscal Year' : 'السنة المالية',
    account: currentLang === 'de' ? 'Konto' : currentLang === 'en' ? 'Account' : 'الحساب',
    code: currentLang === 'de' ? 'Kto-Nr.' : currentLang === 'en' ? 'Code' : 'كود',
    period: currentLang === 'de' ? 'Zeitraum' : currentLang === 'en' ? 'Period' : 'الفترة',
    openingBal: currentLang === 'de' ? 'Anfangsbestand' : currentLang === 'en' ? 'Opening Balance' : 'الرصيد الافتتاحي',
    totalDebit: currentLang === 'de' ? 'Summe Soll (+)' : currentLang === 'en' ? 'Total Debit (+)' : 'إجمالي المدين (+)',
    totalCredit: currentLang === 'de' ? 'Summe Haben (-)' : currentLang === 'en' ? 'Total Credit (-)' : 'إجمالي الدائن (-)',
    closingBal: currentLang === 'de' ? 'Schlussbestand' : currentLang === 'en' ? 'Net Closing Balance' : 'صافي الرصيد الختامي',
    notes: currentLang === 'de' ? 'Hinweise' : currentLang === 'en' ? 'Notes' : 'ملاحظات',
    accountant: currentLang === 'de' ? 'Erstellt von (Buchhalter)' : currentLang === 'en' ? 'Prepared by Accountant' : 'إعداد المحاسب المسؤول',
    auditor: currentLang === 'de' ? 'Finanzprüfung / Revision' : currentLang === 'en' ? 'Financial Audit & Review' : 'المراجعة والتدقيق المالي',
    management: currentLang === 'de' ? 'Genehmigung & Stempel' : currentLang === 'en' ? 'Management Seal & Approval' : 'اعتماد وختم الإدارة',
    footer: currentLang === 'de'
      ? `Offizieller Finanzbericht generiert vom Al-Roeya ERP-System • Alle Rechte vorbehalten © ${new Date().getFullYear()}`
      : currentLang === 'en'
      ? `Official financial statement generated by Al-Roeya ERP System • All rights reserved © ${new Date().getFullYear()}`
      : `تم استخراج هذا التقرير المالي رسميّاً عبر نظام الرؤية المحاسبي الشامل ERP • كافة الحقوق محفوظة © ${new Date().getFullYear()}`
  };

  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.left = '-9999px';
  container.style.top = '-9999px';
  container.style.width = '880px';
  container.style.backgroundColor = '#ffffff';
  container.style.color = '#0f172a';
  container.style.fontFamily = isRtl ? "'Tajawal', 'Segoe UI', Tahoma, sans-serif" : "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  container.style.padding = '35px 40px';
  container.style.direction = dir;
  container.style.boxSizing = 'border-box';

  container.innerHTML = `
    <div style="border-bottom: 2.5px solid #1e3a8a; padding-bottom: 18px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; gap: 16px;">
      <div style="display: flex; align-items: center; gap: 14px;">
        ${settings.logoUrl ? `
          <div style="width: 70px; height: 70px; border-radius: 12px; border: 1px solid #cbd5e1; background: #ffffff; display: flex; align-items: center; justify-content: center; overflow: hidden; flex-shrink: 0; padding: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <img src="${settings.logoUrl}" alt="${settings.companyName}" style="max-width: 100%; max-height: 100%; object-fit: contain;" />
          </div>
        ` : ''}
        <div style="text-align: ${isRtl ? 'right' : 'left'};">
          <div style="font-size: 22px; font-weight: 800; color: #1e3a8a; margin-bottom: 3px;">${settings.companyName}</div>
          <div style="font-size: 11.5px; color: #475569; margin-bottom: 2px;">
            ${labels.cr}: <strong>${settings.commercialRegister || '1010543210'}</strong> | ${labels.vat}: <strong style="color: #1e3a8a;">${settings.taxNumber || '300458921000003'}</strong>
          </div>
          <div style="font-size: 11px; color: #64748b;">${settings.address || 'المقر الرئيسي'} - ${labels.phone}: ${settings.phone || '011-4567890'}</div>
        </div>
      </div>
      <div style="text-align: ${isRtl ? 'left' : 'right'}; background-color: #f8fafc; border: 1px solid #cbd5e1; border-radius: 10px; padding: 9px 14px; font-size: 11px; color: #334155; flex-shrink: 0; line-height: 1.5;">
        <div><strong>${labels.reportDate}:</strong> ${currentDate}</div>
        <div><strong>${labels.issueTime}:</strong> ${currentTime}</div>
        <div><strong>${labels.currency}:</strong> ${curr}</div>
        <div><strong>${labels.fiscalYear}:</strong> ${settings.fiscalYearStart?.slice(0, 4) || '2026'}</div>
      </div>
    </div>

    <div style="background: linear-gradient(135deg, #1e3a8a 0%, #1e293b 100%); color: #ffffff; border-radius: 10px; padding: 15px 20px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
      <div>
        <div style="font-size: 18px; font-weight: 800; margin-bottom: 3px;">${opts.title}</div>
        <div style="font-size: 12.5px; color: #cbd5e1;">
          ${labels.account}: <strong>${opts.accountName}</strong> ${opts.accountCode ? `(${labels.code}: ${opts.accountCode})` : ''} ${opts.accountType ? `• ${opts.accountType}` : ''}
        </div>
      </div>
      ${opts.period ? `<div style="background: rgba(255,255,255,0.15); border: 1px solid rgba(255,255,255,0.25); border-radius: 6px; padding: 5px 12px; font-size: 11.5px; font-weight: 700;">${labels.period}: ${opts.period}</div>` : ''}
    </div>

    ${opts.openingBalance !== undefined || opts.closingBalance !== undefined ? `
      <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 20px;">
        <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px; text-align: center;">
          <div style="font-size: 10.5px; color: #64748b; font-weight: 700; margin-bottom: 3px;">${labels.openingBal}</div>
          <div style="font-size: 14px; font-weight: 800; color: #334155; font-family: monospace;">${(opts.openingBalance || 0).toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${curr}</div>
        </div>
        <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 10px; text-align: center;">
          <div style="font-size: 10.5px; color: #1e40af; font-weight: 700; margin-bottom: 3px;">${labels.totalDebit}</div>
          <div style="font-size: 14px; font-weight: 800; color: #1e3a8a; font-family: monospace;">${(opts.totalDebit || 0).toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${curr}</div>
        </div>
        <div style="background: #faf5ff; border: 1px solid #e9d5ff; border-radius: 8px; padding: 10px; text-align: center;">
          <div style="font-size: 10.5px; color: #6b21a8; font-weight: 700; margin-bottom: 3px;">${labels.totalCredit}</div>
          <div style="font-size: 14px; font-weight: 800; color: #7e22ce; font-family: monospace;">${(opts.totalCredit || 0).toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${curr}</div>
        </div>
        <div style="background: ${(opts.closingBalance || 0) < 0 ? '#fef2f2' : '#f0fdf4'}; border: 1px solid ${(opts.closingBalance || 0) < 0 ? '#fecaca' : '#bbf7d0'}; border-radius: 8px; padding: 10px; text-align: center;">
          <div style="font-size: 10.5px; color: ${(opts.closingBalance || 0) < 0 ? '#991b1b' : '#166534'}; font-weight: 700; margin-bottom: 3px;">${labels.closingBal}</div>
          <div style="font-size: 15px; font-weight: 900; color: ${(opts.closingBalance || 0) < 0 ? '#b91c1c' : '#15803d'}; font-family: monospace;">${(opts.closingBalance || 0).toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${curr}</div>
        </div>
      </div>
    ` : ''}

    <div style="margin-bottom: 22px;">
      <table style="width: 100%; border-collapse: collapse; font-size: 11px; text-align: ${isRtl ? 'right' : 'left'};">
        <thead>
          <tr style="background-color: #1e3a8a; color: #ffffff;">
            ${opts.headers.map(h => `<th style="padding: 9px 8px; border: 1px solid #1e3a8a; font-weight: 700;">${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${opts.rows.map((row, idx) => `
            <tr style="background-color: ${idx % 2 === 0 ? '#ffffff' : '#f8fafc'};">
              ${row.map((cell) => {
                const isNum = typeof cell === 'number' || (!isNaN(Number(cell)) && cell !== '' && typeof cell === 'string' && /^[0-9,.-]+$/.test(String(cell).trim()));
                const numStyle = isNum ? 'font-family: monospace; font-weight: 600;' : '';
                return `<td style="padding: 7px 8px; border: 1px solid #e2e8f0; color: #334155; ${numStyle}">${cell !== undefined && cell !== null ? cell : '-'}</td>`;
              }).join('')}
            </tr>
          `).join('')}
        </tbody>
        ${opts.totals && opts.totals.length > 0 ? `
          <tfoot>
            ${opts.totals.map(tot => `
              <tr style="background-color: #e2e8f0; font-weight: 800; border-top: 2px solid #334155;">
                <td colspan="${Math.max(1, opts.headers.length - 1)}" style="padding: 8px 9px; border: 1px solid #cbd5e1; text-align: ${isRtl ? 'right' : 'left'};">${tot.label}</td>
                <td style="padding: 8px 9px; border: 1px solid #cbd5e1; text-align: ${isRtl ? 'right' : 'left'}; font-family: monospace; font-size: 11.5px; color: ${tot.isDebit ? '#1e3a8a' : tot.isCredit ? '#7e22ce' : '#0f172a'};">${typeof tot.value === 'number' ? tot.value.toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : tot.value}</td>
              </tr>
            `).join('')}
          </tfoot>
        ` : ''}
      </table>
    </div>

    ${opts.notes ? `
      <div style="background-color: #f1f5f9; ${isRtl ? 'border-right' : 'border-left'}: 4px solid #3b82f6; padding: 9px 14px; border-radius: 6px; font-size: 11px; color: #475569; margin-bottom: 25px;">
        <strong>${labels.notes}:</strong> ${opts.notes}
      </div>
    ` : ''}

    <div style="display: flex; justify-content: space-around; margin-top: 35px; padding-top: 18px; border-top: 1px dashed #cbd5e1; page-break-inside: avoid;">
      <div style="text-align: center; width: 170px;">
        <div style="font-size: 11.5px; font-weight: 700; color: #334155; margin-bottom: 35px;">${labels.accountant}</div>
        <div style="border-bottom: 1px solid #94a3b8; width: 100%;"></div>
      </div>
      <div style="text-align: center; width: 170px;">
        <div style="font-size: 11.5px; font-weight: 700; color: #334155; margin-bottom: 35px;">${labels.auditor}</div>
        <div style="border-bottom: 1px solid #94a3b8; width: 100%;"></div>
      </div>
      <div style="text-align: center; width: 170px;">
        <div style="font-size: 11.5px; font-weight: 700; color: #334155; margin-bottom: 35px;">${labels.management}</div>
        <div style="border-bottom: 1px solid #94a3b8; width: 100%;"></div>
      </div>
    </div>

    <div style="margin-top: 30px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 8px;">
      ${labels.footer}
    </div>
  `;

  return container;
}

/**
 * توليد ملف PDF حقيقي عالي الجودة وتحميله أو إرجاع الـ Blob الخاص به
 */
export async function generateAccountPdfBlob(opts: AccountPdfOptions): Promise<{
  blob: Blob;
  filename: string;
  download: () => void;
}> {
  const container = generateAccountHtmlDocument(opts);
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2, // دقة عالية جداً
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    });

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pdfWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    // الصفحة الأولى
    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    // في حال كان التقرير طويلاً ويتجاوز الصفحة الأولى
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    const cleanName = (opts.accountName || 'حساب').replace(/[\/\\:*?"<>|]/g, '_');
    const filename = `كشف_حساب_${cleanName}_${new Date().toISOString().slice(0, 10)}.pdf`;
    const blob = pdf.output('blob');

    const download = () => {
      pdf.save(filename);
    };

    return { blob, filename, download };
  } finally {
    if (document.body.contains(container)) {
      document.body.removeChild(container);
    }
  }
}

/**
 * دالة ذكية لمشاركة وإرسال كشف الحساب وملف الـ PDF عبر الواتساب مباشرة
 */
export async function shareAccountPdfViaWhatsApp(
  phone: string,
  messageText: string,
  opts: AccountPdfOptions
): Promise<void> {
  try {
    customAlert('جاري توليد ملف كشف الحساب بصيغة PDF وتجهيز إرساله عبر الواتساب...', 'info');
    const { blob, filename, download } = await generateAccountPdfBlob(opts);

    // 1. تنزيل ملف الـ PDF فورياً لدى المستخدم ليكون جاهزاً للإرفاق
    download();

    // 2. فحص دعم المتصفح لمشاركة الملفات الحقيقية (Web Share API)
    const file = new File([blob], filename, { type: 'application/pdf' });
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          title: opts.title,
          text: messageText,
          files: [file]
        });
        customAlert('تم فتح قائمة المشاركة لإرسال ملف الـ PDF مباشرة إلى الواتساب!', 'success');
        return;
      } catch (shareErr: any) {
        if (shareErr.name !== 'AbortError') {
          console.log('Share API fallback to WhatsApp link');
        }
      }
    }

    // 3. فتح تطبيق الواتساب المباشر بالرقم أو فتح واتساب العام لاختيار أي محادثة
    const cleaned = cleanPhoneNumber(phone);
    const enrichedMessage = `${messageText}\n\n📎 *تم استخراج وتنزيل ملف كشف الحساب الرسمي المعتمد (${filename}) بصيغة PDF بنجاح لتقديمه للمطابقة.*`;
    const encoded = encodeURIComponent(enrichedMessage);
    const waUrl = cleaned
      ? `https://wa.me/${cleaned}?text=${encoded}`
      : `https://api.whatsapp.com/send?text=${encoded}`;

    window.open(waUrl, '_blank');
    if (cleaned) {
      customAlert(`تم تنزيل ملف الـ PDF وفتح محادثة واتساب للرقم (${cleaned}) فورياً!`, 'success');
    } else {
      customAlert('تم تنزيل ملف الـ PDF وفتح واتساب العام لتحديد واختيار المرسل إليه من محادثاتك مباشرة!', 'success');
    }
  } catch (error: any) {
    console.error('PDF Share Error:', error);
    customAlert('حدث خطأ أثناء توليد ملف الـ PDF، يرجى إعادة المحاولة.', 'error');
  }
}
